### ISSUE TITLE
App fails to read config file if it has entries in incorrect order

### ISSUE THREAD

**Issue by danielskowronski** [Hong5489/ir_remote#3]
Unless the config file follows the format described in `example.txt` strictly keeping line order, the app will fail to read some entries, returning error `Could not read ${STRING} string`. 

I think it's because `flipper_format_read_string` (at least in `unlshd-026`) does not reset file stream offset. For example, since `DOWN` is read after `UP`, if you change the order of lines in config (`DOWN` before `UP`) it'll execute like that: 

- after `REMOTE` is read, seek `UP` entry (skipping `DOWN` line)
- read `UP` entry
- advance offset to position after `UP` ends
- subsequent attempt to read `DOWN` fails as it's not present in the rest of the file

If that's not deliberate, then documentation is missing this constraint.

**Comment by Hong5489** [comment]
I fixed the issue, you can try download the latest version
