### ISSUE TITLE
Option to disable hold-repeat

### ISSUE THREAD

**Issue by pixelatedmirror** [Hong5489/ir_remote#5]
I have a remote with more than 6 buttons I'd like to use with this app, but repeating commands don't make sense for the device I'm controlling (robotic vacuum).  I'd like to use the hold options for different one-shot commands. Is there a way we could differentiate between repeating and non-repeating hold commands in the config file?

**Comment by Hong5489** [comment]
Sorry for the delay, I just added a config to disable the repeat signal. Just need to add `REPEATSIGNAL: false` in your config file. 
You can refer to the README and download the latest release file
